### ISSUE TITLE
Snake moves faster in vertical direction than when horizontal

### ISSUE THREAD

**Issue by denvaar** [denvaar/snek#16]
One not very nice side effect is that since console cells are taller than they are wide, the movement of the snake appears faster when moving vertically.

I'm not sure if there's a "code solution" for this, but if anyone has any bright ideas, I am open to suggestions.

**Comment by smcveigh941** [comment]
Hmm.. If we could find out the ratio of the height/width of the cells we could divide the speed by that ratio when moving vertically.

I'm not sure whether that ratio would be the same across different terminal applications.

**Comment by denvaar** [comment]
Yeah that could be a good option. I wonder if Node has an API for finding info like that about the terminal.

**Comment by louisgjohnson** [comment]
isn't the height and width for the view fixed though? maybe changing the timeout seconds depending on the direction should do the trick

**Comment by denvaar** [comment]
> isn't the height and width for the view fixed though? maybe changing the timeout seconds depending on the direction should do the trick

The height and width that we're referring to is the individual cells in the console. It can be configured in your terminal settings, I believe (iTerm, Terminal.app, etc.)

Yeah, I think changing the timeout seconds depending on direction would help.

**Comment by denvaar** [comment]
You're PR made it much more playable, thanks @louisgjohnson
