### ISSUE TITLE
Game Over Animation

### ISSUE THREAD

**Issue by mahowa** [denvaar/snek#33]
Would be awesome to see a game over animation

**Comment by mahowa** [comment]
<img width="703" alt="Screen Shot 2019-10-08 at 9 36 50 AM" src="https://user-images.githubusercontent.com/8989577/66410394-4785a400-e9af-11e9-8ef3-d6e120f30525.png">

**Comment by mahowa** [comment]
[GAMEOVER.csv.zip](https://github.com/denvaar/snek/files/3703315/GAMEOVER.csv.zip)

**Comment by laercios** [comment]
I made this screen using 'GAMEOVER.csv' https://github.com/denvaar/snek/pull/39
