### ISSUE TITLE
Hide cursor when game is playing

### ISSUE THREAD

**Issue by denvaar** [denvaar/snek#34]
`'\x1b[?25l'` will hide the cursor.

`'\x1b[?25h'` will show the cursor (need to run this when the game is exited either via ctrl-c or if the snek dies.

**Comment by k1dnyy** [comment]
Can I have dibs on this issue?

**Comment by denvaar** [comment]
Go for it

**Comment by laercios** [comment]
I created a pull request https://github.com/denvaar/snek/pull/38
