### ISSUE TITLE
Improve performance of screen drawing

### ISSUE THREAD

**Issue by denvaar** [denvaar/snek#8]
I think process.stdout and process.stdin would provide better performance in terms of rendering the view. Instead of using `console.log` as the function that draws the game scene on each loop tick, try using process.stdout instead to see if it looks better.

**Comment by sudhir512kj** [comment]
@denvaar I would like to work on it.

**Comment by denvaar** [comment]
@sudhir512kj awesome! Here's an example that might have some useful insights in case you need it: https://github.com/mdibaiee/node-games/blob/dd48a879c243228ca99dd974c8f032f4e6186ff9/src/classes/interface.js

**Comment by sudhir512kj** [comment]
@denvaar I will start it today

**Comment by louisgjohnson** [comment]
made a PR for this

**Comment by denvaar** [comment]
I want to leave this open a bit longer, because I wonder if there's a way to only update cells that need to change. If there's a way to only update cells that change, and if it can be done efficiently, I think that'd be really cool. So, still open for now.

**Comment by denvaar** [comment]
Here is an example of what I am talking about with this issue.

![image](https://user-images.githubusercontent.com/10538978/66275158-29029a00-e843-11e9-9c7e-ecd40f45a466.png)

These are two versions of a game loop. The first one uses ANSI escape codes to the output. When `gameLoopANSI` is run, the cursor is moved to 10,10 on the console, and then the date is written. There is no need to clear the console on each loop iteration. As a result, if you scroll up in your console window after the program is done running, you will not see a brand new scene for each iteration.

The second function, `gameLoop` writes an entire new screen of output each iteration, and if you scroll back in your console history, you see each iteration there in your history.

I would love to switch this game to perform more like `gameLoopANSI`.

**Comment by vypxl** [comment]
I would like to try that
